export const TUI_COPY = {
	sessionSelector: {
		titleCurrent: "恢复会话（当前目录）",
		titleAll: "恢复会话（全部）",
		scopeCurrent: "当前目录",
		scopeAll: "全部",
		sortLabel: "排序",
		nameLabel: "名称",
		sortThreaded: "树形",
		sortRecent: "最近",
		sortRelevance: "相关",
		nameAll: "全部",
		nameNamed: "仅命名",
		toggleScope: "切换范围",
		toggleSort: "切换排序",
		toggleNamed: "仅命名",
		deleteHint: "删除",
		renameHint: "重命名",
		pathState: (enabled: boolean) => `路径 ${enabled ? "开" : "关"}`,
		loading: (progressText: string) => `加载中 ${progressText}`,
		searchRegexHint: "re:<模式> 正则",
		searchExactHint: '"短语" 精确匹配',
		deleteConfirm: "确认删除这个会话？",
		noNamedAll: (toggleKey: string) => `  没有已命名会话。按 ${toggleKey} 查看全部。`,
		noNamedCurrent: (toggleKey: string) => `  当前目录没有已命名会话。按 ${toggleKey} 查看全部，或按 Tab 查看全局。`,
		noSessionsAll: "  没有找到会话",
		noSessionsCurrent: "  当前目录没有会话。按 Tab 查看全部。",
		deleteCurrentError: "不能删除当前正在使用的会话",
		trashed: "会话已移到回收站",
		deleted: "会话已删除",
		failedLoad: (message: string) => `加载会话失败：${message}`,
		failedDelete: (message: string) => `删除会话失败：${message}`,
		unknownError: "未知错误",
		renameTitle: "重命名会话",
		renameInputLabel: "会话名（留空则移除）：",
		renameSave: "保存",
		renameCancel: "取消",
		deleteConfirmAction: "确认",
		deleteCancelAction: "取消",
		relativeNow: "刚刚",
		relativeMinutes: (value: number) => `${value}分`,
		relativeHours: (value: number) => `${value}小时`,
		relativeDays: (value: number) => `${value}天`,
		relativeWeeks: (value: number) => `${value}周`,
		relativeMonths: (value: number) => `${value}月`,
		relativeYears: (value: number) => `${value}年`,
	},
	loginDialog: {
		title: (providerName: string) => `登录 ${providerName}`,
		cancelled: "登录已取消",
		clickHint: (modifier: string) => `${modifier}+单击打开`,
		cancel: "取消",
		submit: "提交",
		close: "关闭",
		example: (placeholder: string) => `例如：${placeholder}`,
		pasteRedirectUrl: "请粘贴回跳 URL，或直接在浏览器中完成登录：",
		waitingBrowserAuth: "正在等待浏览器认证完成...",
		waitingDeviceAuth: "正在等待设备码认证完成...",
		browserAuthStatus: "等待中 · 浏览器认证",
		waitingProviderLogin: (providerName: string) => `等待中 · 登录 ${providerName}`,
		waitingProviderBrowserLogin: (providerName: string) => `等待中 · 请在浏览器中完成 ${providerName} 登录`,
		waitingPrompt: (message: string) => `等待中 · ${message}`,
		apiKeyPrompt: "请输入 API 密钥：",
		apiKeyEmpty: "API 密钥不能为空。",
		deviceCode: (code: string) => `验证码：${code}`,
		deviceExpiresIn: (seconds: number) => `请在 ${seconds} 秒内完成认证`,
	},
	loginSelector: {
		authTypeTitle: "请选择登录方式：",
		subscription: "使用订阅登录",
		apiKey: "使用 API 密钥",
	},
	themeSelector: {
		current: "（当前）",
	},
	oauthSelector: {
		loginTitle: "选择要配置的模型提供方：",
		logoutTitle: "选择要退出登录的模型提供方：",
		noAvailableProviders: "当前没有可用的模型提供方",
		noLoggedInProviders: "当前没有已登录的模型提供方，请先使用 /login。",
		noMatchingProviders: "没有匹配的模型提供方",
		configured: " ✓ 已配置",
		subscriptionConfigured: "订阅已配置",
		apiKeyConfigured: "API 密钥已配置",
		defaultApiKeyLabel: "API 密钥",
		notConfigured: " • 未配置",
		envApiKey: (label: string) => ` ✓ 环境变量: ${label}`,
		runtimeApiKey: " ✓ 运行时 API 密钥",
		customApiKey: " ✓ 自定义 API 密钥",
		modelsJsonKey: " ✓ models.json 中的密钥",
		modelsJsonCommand: " ✓ models.json 中的命令",
	},
	extensionSelector: {
		navigate: "上下移动",
		select: "确认",
		cancel: "取消",
	},
	extensionInput: {
		submit: "提交",
		cancel: "取消",
	},
	scopedModelsSelector: {
		title: "模型范围配置",
		sessionOnly: (saveKey: string) => `仅当前会话生效。按 ${saveKey} 可保存到设置。`,
		filterHint: "当前只显示已配置模型提供方的模型。可用 /login 添加新的模型提供方。",
		noMatches: "  没有匹配的模型",
		modelName: (name: string) => `  模型名称：${name}`,
		scopeLabel: "范围: ",
		scopeAll: "全部",
		scopeScoped: "限定",
		scopeToggleHint: "切换范围",
		allEnabled: "全部启用",
		enabledCount: (enabled: number, total: number) => `${enabled}/${total} 已启用`,
		toggle: "切换",
		enableAll: "全开",
		clearAll: "清空",
		provider: "同提供方",
		reorder: "重排",
		save: "保存",
		unsaved: "（未保存）",
	},
	thinkingSelector: {
		off: "不启用思考",
		minimal: "极简思考（约 1k tokens）",
		low: "轻量思考（约 2k tokens）",
		medium: "中等思考（约 8k tokens）",
		high: "深入思考（约 16k tokens）",
		xhigh: "最强思考（约 32k tokens）",
	},
	treeSelector: {
		title: "会话树",
		move: "移动",
		page: "翻页",
		foldBranch: "折叠/分支",
		label: "标签",
		filters: "筛选",
		cycle: "循环",
		labelTime: "标签时间",
		searchPrompt: "输入即可搜索：",
		labelInput: "标签（留空则移除）：",
		save: "保存",
		cancel: "取消",
		userPrefix: "用户：",
		assistantPrefix: "助手：",
		assistantAborted: "（已中止）",
		assistantNoContent: "（无内容）",
		compaction: (tokensInThousands: number) => `[压缩: ${tokensInThousands}k tokens]`,
		branchSummaryPrefix: "[分支摘要]: ",
		model: (modelId: string) => `[模型: ${modelId}]`,
		thinking: (level: string) => `[思考: ${level}]`,
		custom: (customType: string) => `[自定义: ${customType}]`,
		labelEntry: (label: string) => `[标签: ${label}]`,
		labelCleared: "[标签: 已清空]",
		titleEntry: (title: string) => `[标题: ${title}]`,
		titleEmpty: "[标题: 空]",
		filterNoTools: " [无工具]",
		filterUserOnly: " [仅用户]",
		filterLabeledOnly: " [仅标签]",
		filterAll: " [全部]",
		labelTimeEnabled: " [+标签时间]",
		noEntries: "  没有找到节点",
		searchRoleUser: "用户",
		searchRoleAssistant: "助手",
		searchRoleBash: "bash",
		searchRoleToolResult: "工具结果",
		searchRoleCompaction: "压缩",
		searchRoleBranchSummary: "分支摘要",
		searchRoleTitle: "标题",
		searchRoleModel: "模型",
		searchRoleThinking: "思考",
		searchRoleCustom: "自定义",
		searchRoleLabel: "标签",
		toolResultFallback: "[工具结果]",
		bashEntryPrefix: "[bash]：",
		customMessagePrefix: (customType: string) => `[${customType}]：`,
	},
	userMessageSelector: {
		noMessages: "  没有可用于分叉的用户消息",
		messagePosition: (position: number, total: number) => `  第 ${position} 条 / 共 ${total} 条消息`,
		title: "从消息分叉",
		description: "选择一条用户消息，把到该节点为止的当前路径复制到新会话中",
	},
	configSelector: {
		resourceConfiguration: "资源配置",
		filterResources: "输入即可筛选资源",
		toggle: "切换启用状态",
		close: "关闭",
		noResources: "  没有找到资源",
		userSettings: "用户设置",
		projectSettings: "项目设置",
		userDir: (baseDir: string) => `用户 (${baseDir})`,
		projectDir: (baseDir: string) => `项目 (${baseDir})`,
		userDefaultDir: "用户 (~/.lumen/agent/)",
		projectDefaultDir: "项目 (.lumen/)",
		extensions: "扩展",
		skills: "技能",
		prompts: "提示模板",
		themes: "主题",
	},
	settingsSelector: {
		booleanOn: "开启",
		booleanOff: "关闭",
		steeringModeOneAtATime: "逐条发送",
		steeringModeAll: "一次全发",
		transportSse: "SSE",
		transportWebsocket: "WebSocket",
		transportWebsocketCached: "WebSocket（缓存）",
		transportAuto: "自动",
		doubleEscapeActionTree: "会话树",
		doubleEscapeActionFork: "分叉",
		doubleEscapeActionNone: "无动作",
		treeFilterModeDefault: "默认",
		treeFilterModeNoTools: "无工具",
		treeFilterModeUserOnly: "仅用户",
		treeFilterModeLabeledOnly: "仅标签",
		treeFilterModeAll: "全部",
		submenuConfirm: "确认",
		submenuCancel: "返回",
		warningsConfigure: "配置",
		warningsLabel: "警告设置",
		warningsDescription: "启用或禁用各类警告",
		anthropicExtraUsageLabel: "Anthropic 额外用量",
		anthropicExtraUsageDescription: "Anthropic 订阅认证可能产生付费额外用量时警告",
		thinkingLevelDescriptions: {
			off: "不推理",
			minimal: "极简推理（~1k tokens）",
			low: "轻度推理（~2k tokens）",
			medium: "中等推理（~8k tokens）",
			high: "深度推理（~16k tokens）",
			xhigh: "最大推理（~32k tokens）",
		},
		thinkingLevelLabels: {
			off: "不推理",
			minimal: "极简",
			low: "轻度",
			medium: "中等",
			high: "深度",
			xhigh: "最大",
		},
		thinkingTitle: "思考等级",
		thinkingLabel: "思考等级",
		thinkingLabelDescription: "支持思考的模型的推理深度",
		thinkingDescription: "选择推理深度（token 消耗越高，思考越深入）",
		themeTitle: "主题",
		themeLabel: "主题",
		themeLabelDescription: "界面颜色主题",
		themeDescription: "选择颜色主题",
		autoCompactLabel: "自动压缩",
		autoCompactDescription: "上下文过大时自动压缩",
		autoCompactThresholdLabel: "压缩阈值占比",
		autoCompactThresholdDescription: "按上下文占比触发自动压缩（留空则改用 reserveTokens）",
		autoCompactThresholdOff: "关闭",
		autoCompactThresholdOptions: ["关闭", "70%", "75%", "80%", "85%", "90%", "95%"],
		submenuSearchHint: "输入搜索 · Enter/Space 切换 · Esc 取消",
		steeringModeLabel: "消息模式",
		steeringModeDescription: "流式输出时按 Enter 排队消息。'one-at-a-time': 逐条发送等回复。'all': 一次全发。",
		followUpModeLabel: "后续消息模式",
		followUpModeDescription: (followUpKey: string) =>
			`${followUpKey} 排队后续消息。'one-at-a-time': 逐条发送等回复。'all': 一次全发。`,
		transportLabel: "传输协议",
		transportDescription: "支持多种传输的 provider 优先使用的协议",
		hideThinkingLabel: "隐藏思考",
		hideThinkingDescription: "控制是否隐藏助手回复中的思考内容",
		toolDisplayModeLabel: "工具折叠",
		toolDisplayModeDescription: "控制工具输出默认是否折叠显示",
		collapseChangelogLabel: "折叠更新日志",
		collapseChangelogDescription: "更新后显示精简版 changelog",
		quietStartupLabel: "安静启动",
		quietStartupDescription: "启动时不显示详细信息",
		installTelemetryLabel: "安装遥测",
		installTelemetryDescription: "更新后发送匿名版本 ping",
		doubleEscapeActionLabel: "双击 Escape 动作",
		doubleEscapeActionDescription: "编辑器为空时连按两次 Escape 的行为",
		treeFilterModeLabel: "树过滤模式",
		treeFilterModeDescription: "打开 /tree 时的默认过滤",
		showImagesLabel: "显示图片",
		showImagesDescription: "在终端内联渲染图片",
		imageWidthLabel: "图片宽度",
		imageWidthDescription: "内联图片的终端字符宽度",
		autoResizeImagesLabel: "自动缩放图片",
		autoResizeImagesDescription: "大图自动缩放到 2000x2000 以提高模型兼容性",
		blockImagesLabel: "屏蔽图片",
		blockImagesDescription: "阻止图片发送给 LLM",
		skillCommandsLabel: "技能命令",
		skillCommandsDescription: "将技能注册为 /skill:name 命令",
		hardwareCursorLabel: "显示硬件光标",
		hardwareCursorDescription: "显示终端光标（支持 IME 输入法定位）",
		editorPaddingLabel: "编辑器边距",
		editorPaddingDescription: "输入框水平边距（0-3）",
		autocompleteMaxVisibleLabel: "自动补全条数",
		autocompleteMaxVisibleDescription: "自动补全下拉框最大显示条数（3-20）",
		clearOnShrinkLabel: "收缩时清空",
		clearOnShrinkDescription: "内容缩短时清除空行（可能闪烁）",
		terminalProgressLabel: "终端进度条",
		terminalProgressDescription: "在终端标签栏显示 OSC 9;4 进度指示器",
	},
	interactiveNotices: {
		migratedCredentials: (providers: string) => `Migrated credentials to auth.json: ${providers}`,
		modelsJsonError: (message: string) => `models.json error: ${message}`,
		tmuxExtendedKeysOff:
			"tmux extended-keys is off. Modified Enter keys may not work. Add `set -g extended-keys on` to ~/.tmux.conf and restart tmux.",
		tmuxExtendedKeysFormatXterm:
			"tmux extended-keys-format is xterm. Pi works best with csi-u. Add `set -g extended-keys-format csi-u` to ~/.tmux.conf and restart tmux.",
		thinkingUnsupported: "Current model does not support thinking",
		thinkingLevelChanged: (level: string) => `Thinking level: ${level}`,
		thinkingBlockVisibility: (hidden: boolean) => `Thinking block: ${hidden ? "hidden" : "visible"}`,
		queueRestoreNone: "No queued messages to restore",
		queueRestored: (count: number) => `Restored ${count} queued message${count === 1 ? "" : "s"} to the composer`,
		modelScopeSingle: "Only one model in scope",
		modelSingleAvailable: "Only one model available",
		modelSwitched: (label: string, thinking?: string) => `Switched to ${label}${thinking ? ` (${thinking})` : ""}`,
		modelSelected: (modelId: string) => `Model: ${modelId}`,
		noAvailableModels: "No models available",
		scopedModelsSaved: "Saved model scope to settings",
		externalEditorMissing: "No external editor configured. Set $VISUAL or $EDITOR first.",
		copyNoAssistantMessage: "No assistant message available to copy yet.",
		copyLastAssistantMessage: "Copied the latest assistant message to the clipboard",
		noForkableMessages: "No messages available to fork from",
		forkedToNewSession: "Forked to a new session",
		noClonableContent: "No content available to clone",
		clonedToNewSession: "Cloned into a new session",
		treeEmpty: "This session does not have any nodes yet",
		alreadyAtTreeNode: "Already at that node",
		branchSummaryCancelled: "Branch summary cancelled",
		treeJumpCancelled: "Navigation cancelled",
		treeJumped: "Jumped to the selected node",
		sessionResumed: "Resumed session",
		sessionResumeCancelled: "Session resume cancelled",
		sessionResumedWithOverride: "Resumed session in the current working directory",
		autoCompactionCancelled: "Auto-compaction cancelled",
		compactionQueuedMessage: "Queued message for send after compaction finishes",
		compactionSessionCount: (count: number) =>
			`This session has been compacted ${count} time${count === 1 ? "" : "s"}`,
		windowsSuspendUnsupported: "Suspend is not supported on Windows yet",
		errorPrefix: "Error: ",
		warningPrefix: "Warning: ",
		fatalCreateSession: "Failed to create session",
		fatalForkSession: "Failed to fork session",
		fatalResumeSession: "Failed to resume session",
		fatalImportSession: "Failed to import session",
		connectionRecovered: "Connection restored",
		reconnectingStream: "Connection unstable, recovering stream",
		reconnectAttemptDetail: (attempt: number, maxAttempts: number) =>
			`SSE reconnect · attempt ${attempt}/${maxAttempts}`,
		approvalWaiting: "Awaiting approval",
		choiceWaiting: "Awaiting your choice",
		inputWaiting: "Awaiting your input",
		compactingConversation: "Compacting conversation",
		autoCompactingAfterOverflow: "Auto-compacting after overflow",
		autoCompactingConversation: "Auto-compacting conversation",
		manualCompactionCancelled: "Compaction cancelled",
		autoRetryingRequest: "Request unstable, retrying automatically",
		requestFailed: "Request failed",
		retryFailureDetail: (attempt: number) => `Retried ${attempt} time${attempt === 1 ? "" : "s"}`,
		retryAttemptDetail: (attempt: number, maxAttempts: number, message: string) =>
			`Attempt ${attempt}/${maxAttempts} · ${message}`,
		retryResumeDetail: (attempt: number, maxAttempts: number, seconds: number) =>
			`Attempt ${attempt}/${maxAttempts} · retrying in ${seconds}s`,
		retryFailedAfterAttempts: (attempt: number, finalError: string) =>
			`Retry failed after attempt ${attempt}: ${finalError}`,
		cancelHint: (interruptKey: string) => `${interruptKey} to cancel`,
		noOAuthProviders: "No subscription-login providers are currently available.",
		noApiKeyProviders: "No API-key login providers are currently available.",
		noStoredCredentials:
			"No saved credentials available to remove. /logout only removes credentials saved via /login and does not modify environment variables or models.json.",
		loggedOutProvider: (providerName: string) => `Logged out of ${providerName}`,
		removedSavedApiKey: (providerName: string) =>
			`Removed the saved API key for ${providerName}. Environment variables and models.json were not changed.`,
		loginSavedAuth: (providerName: string, authPath: string) => `Saved ${providerName} credentials to ${authPath}`,
		loginSelectedModel: (actionLabel: string, modelId: string, authPath: string) =>
			`${actionLabel}. Selected ${modelId}. Saved credentials to ${authPath}`,
		loginSavedOnly: (actionLabel: string, authPath: string) => `${actionLabel}. Saved credentials to ${authPath}`,
		reloadWhileStreaming: "Wait for the current response to finish before reloading.",
		reloadWhileCompacting: "Wait for compaction to finish before reloading.",
		reloadingResources: "Reloading keybindings, extensions, skills, prompts, and themes...",
		reloadComplete: "Reloaded keybindings, extensions, skills, prompts, and themes",
		exportedSession: (path: string) => `Exported session to: ${path}`,
		exportFailed: (message: string) => `Failed to export session: ${message}`,
		importFailed: (message: string) => `Failed to import session: ${message}`,
		importUsage: "Usage: /import <path.jsonl>",
		importCancelled: "Import cancelled",
		importComplete: (path: string) => `Imported session from: ${path}`,
		sessionNameCurrent: (name: string) => `Session name: ${name}`,
		sessionNameUpdated: (name: string) => `Set session name to: ${name}`,
		shareCancelled: "Share cancelled",
		shareAuthRequired: "GitHub CLI is not logged in. Run `gh auth login` first.",
		shareCliMissing: "GitHub CLI (gh) is not installed. Install it from https://cli.github.com/ first.",
		shareGistCreateFailed: (message: string) => `Failed to create gist: ${message}`,
		shareGistIdMissing: "Could not parse a gist ID from gh output",
		sharePreviewUrl: (url: string) => `Share URL: ${url}`,
		shareGistUrl: (url: string) => `Gist: ${url}`,
		bashExecutionFailed: (message: string) => `Bash command failed: ${message}`,
		bashAlreadyRunning: "A bash command is already running. Press Esc to cancel it first.",
		noCompactionContent: "Nothing to compact yet",
		branchSummaryRunning: (interruptKey: string) => `Summarizing branch... (${interruptKey} to cancel)`,
		logoutFailed: (message: string) => `Logout failed: ${message}`,
		saveApiKeyFailed: (providerName: string, message: string) =>
			`Failed to save API key for ${providerName}: ${message}`,
		loginFailed: (providerName: string, message: string) => `Login failed for ${providerName}: ${message}`,
		loginCancelled: "登录已取消",
		reloadFailed: (message: string) => `Reload failed: ${message}`,
		creatingGist: "Creating gist...",
		themeLoadFailed: (themeName: string, error: string) =>
			`Failed to load theme "${themeName}": ${error}\nFell back to dark theme.`,
		nameUsage: "Usage: /name <name>",
		unknownError: "Unknown error",
	},
	queueLabels: {
		followUp: "Follow-up",
		steering: "Steering",
		sendFailed: (multiple: boolean, message: string) =>
			`Failed to send queued message${multiple ? "s" : ""}: ${message}`,
	},
	missingSessionCwd: {
		title: "会话工作目录不存在",
	},
	loadedResources: {
		context: "上下文",
		skills: "技能",
		prompts: "提示模板",
		extensions: "扩展",
		themes: "主题",
		skillConflicts: "[技能冲突]",
		promptConflicts: "[提示模板冲突]",
		extensionIssues: "[扩展问题]",
		themeConflicts: "[主题冲突]",
	},
	sessionInfo: {
		title: "会话信息",
		name: "名称：",
		file: "文件：",
		memoryOnly: "仅内存",
		id: "ID：",
		messageStats: "消息统计",
		user: "用户：",
		assistant: "助手：",
		toolCalls: "工具调用：",
		toolResults: "工具结果：",
		total: "总计：",
		tokens: "Tokens",
		input: "输入：",
		output: "输出：",
		cacheRead: "缓存读取：",
		cacheWrite: "缓存写入：",
		cost: "成本",
	},
	changelog: {
		title: "Lumen 更新日志",
		empty: "当前没有可显示的更新记录。",
		open: "打开更新日志",
	},
	importDialog: {
		title: "导入会话",
		replacePrompt: (path: string) => `要用 ${path} 替换当前会话吗？`,
	},
	branchSummaryDialog: {
		title: "要总结当前分支吗？",
		noSummary: "不总结",
		directSummary: "直接总结",
		customSummary: "自定义提示词总结",
		customPromptTitle: "请输入自定义总结提示词",
	},
	bedrockDialog: {
		title: "Amazon Bedrock 配置说明",
		line1: "Amazon Bedrock 使用 AWS 凭据，不是单独的一条 API 密钥。",
		line2: "请先配置 AWS profile、IAM 密钥、bearer token，或基于角色的凭据。",
		reference: "参考：",
	},
	startupHeader: {
		interrupt: "中断当前回复",
		clear: "清空输入框",
		exitLumen: "退出 Lumen",
		exitWhenEmpty: "在输入框为空时退出",
		suspend: "挂起到后台",
		deleteToLineEnd: "删除到行尾",
		cycleThinking: "切换思考等级",
		cycleModels: "循环切换模型",
		openModelSelector: "打开模型选择器",
		expandToolOutput: "展开工具输出",
		expandThinking: "展开思考内容",
		openExternalEditor: "打开外部编辑器",
		openCommandMenu: "打开命令菜单",
		runBash: "运行 bash",
		runBashExcluded: "运行 bash（不写入上下文）",
		queueFollowUp: "排队后续消息",
		editQueuedMessages: "编辑全部排队消息",
		pasteClipboardImage: "粘贴剪贴板图片",
		attachFiles: "附加文件",
		interruptShort: "中断",
		clearExitShort: "清空/退出",
		commandShort: "命令",
		moreShort: "更多",
		compactOnboarding: (expandKey: string) => `按 ${expandKey} 查看完整启动帮助和已加载资源。`,
		onboarding: "Lumen 可以解释自己的功能，也能查询本地文档。直接问它怎么使用或扩展 Lumen 即可。",
	},
	updateNotification: {
		openChangelog: "打开更新日志",
		changelogLabel: "Lumen 更新日志：",
		newVersionTitle: "发现新版本",
		newVersionInstruction: (newVersion: string) => `发现新版本 ${newVersion}，运行 `,
		packageUpdateTitle: "发现插件更新",
		packageUpdateInstruction: "发现插件更新，运行 ",
		packagesLabel: "插件：",
	},
	newSession: {
		started: "✓ 已开始新会话",
	},
	compatibilityView: {
		packages: "[插件兼容性]",
		extensions: "[扩展问题]",
		skills: "[技能问题]",
		ok: "[兼容性]",
		okBody: "  当前没有检测到插件、扩展或技能兼容性问题。",
		next: "下一步：",
		nextFix: "  1. 修复或适配不兼容的插件/技能。",
		nextReload: "  2. 运行 /reload 重新检查当前会话。",
		nextRemove: "  3. 如果仍然失败，就移除插件/package 或删除 skill。",
		removeHint: (appName: string, source: string) =>
			`    - 如果始终不兼容，请用 "${appName} remove ${source}" 移除。`,
	},
	collapsedToolGroup: {
		reading: (count: number) => `Reading ${count} file${count === 1 ? "" : "s"}`,
		readCompleted: (count: number) => `Read ${count} file${count === 1 ? "" : "s"}`,
		searching: (count: number) => `Searching ${count} pattern${count === 1 ? "" : "s"}`,
		searchCompleted: (count: number) => `Searched ${count} pattern${count === 1 ? "" : "s"}`,
		listing: (count: number) => `Listing ${count} ${count === 1 ? "directory" : "directories"}`,
		listCompleted: (count: number) => `Listed ${count} ${count === 1 ? "directory" : "directories"}`,
		readLabel: "Read",
		searchLabel: "Search",
		listLabel: "List",
	},
	progressSurface: {
		plan: "Plan",
		next: "Next",
		tip: "提示",
		tips: {
			clearContext: "切换话题前可先用 /clear 释放上下文",
			queueHint: "Enter 会在下一个工具间隙发送，Alt+Enter 会排队到本轮结束后再发",
			tasksHint: "任务栏展开/收起能力正在继续收口进 core，当前先保持紧凑视图",
			contextPressure: "上下文快满了，可以用 /clear，或等待自动压缩",
		},
		idle: "Idle",
		pending: "pending",
		thinking: "thinking",
		thinkingDuration: (seconds: number) => `${seconds}s thinking`,
		runningTask: (count: number) => `${count} running task${count === 1 ? "" : "s"}`,
		toolUses: (count: number) => `${count} use${count === 1 ? "" : "s"}`,
		moreExecutionItems: (count: number) => `${count} more execution item${count === 1 ? "" : "s"}`,
		moreTasks: (count: number) => `${count} more task${count === 1 ? "" : "s"}`,
		executionDetailPrefix: "tool",
	},
	hotkeys: {
		title: "快捷键说明",
		navigation: "移动",
		editing: "编辑",
		other: "其他",
		extensions: "扩展",
		key: "按键",
		action: "作用",
		moveCursor: "移动光标 / 浏览历史（输入框为空时按上键）",
		moveByWord: "按单词移动",
		lineStart: "移动到行首",
		lineEnd: "移动到行尾",
		jumpForward: "向前跳到字符",
		jumpBackward: "向后跳到字符",
		scrollPage: "按页滚动",
		sendMessage: "发送消息",
		newLine: "插入新行",
		newLineWindowsTerminal: "插入新行（Windows Terminal 中使用 Ctrl+Enter）",
		deleteWordBackward: "向后删除一个单词",
		deleteWordForward: "向前删除一个单词",
		deleteToLineStart: "删除到行首",
		deleteToLineEnd: "删除到行尾",
		yank: "粘贴最近一次删除的文本",
		yankPop: "粘贴后轮换已删除文本",
		undo: "撤销",
		pathCompletion: "路径补全 / 接受自动补全",
		cancelAutocomplete: "取消自动补全 / 中止流式输出",
		clearOrExit: "先清空输入框，再次触发则退出",
		exitWhenEmpty: "输入框为空时退出",
		suspend: "挂起到后台",
		cycleThinking: "切换思考等级",
		cycleModels: "循环切换模型",
		openModelSelector: "打开模型选择器",
		toggleToolExpansion: "切换工具输出展开状态",
		toggleThinking: "切换思考内容显示",
		openExternalEditor: "在外部编辑器中编辑消息",
		queueFollowUp: "排队后续消息",
		restoreQueued: "恢复排队消息",
		pasteImage: "粘贴剪贴板图片",
		slashCommands: "打开命令菜单",
		runBash: "运行 bash 命令",
		runBashExcluded: "运行 bash 命令（不写入上下文）",
	},
	bashExecution: {
		running: (cancelKey: string) => `Running... (${cancelKey} to cancel)`,
		cancelled: "(cancelled)",
		moreLines: (count: number) => `... ${count} more line${count === 1 ? "" : "s"}`,
		expandHint: "expand",
		collapseHint: "collapse",
		truncatedOutput: (fullOutputPath: string) => `Output truncated. Full output: ${fullOutputPath}`,
	},
	toolSummary: {
		running: "Running…",
		completed: (parts: string) => `Done (${parts})`,
		runningBatch: (parts: string) => `Running (${parts})`,
	},
	thinkingBlock: {
		fullTitle: "∴ Thinking…",
		thinkingPlaceholder: "Thinking…",
		aborted: "Aborted",
		errorPrefix: "Error: ",
	},
} as const;
