export const TUI_COPY = {
	sessionSelector: {
		titleCurrent: "恢复会话（当前目录）",
		titleAll: "恢复会话（全部）",
		scopeCurrent: "当前目录",
		scopeAll: "全部",
		sortLabel: "排序",
		nameLabel: "名称",
		sortThreaded: "树形",
		sortRecent: "最近",
		sortRelevance: "相关",
		nameAll: "全部",
		nameNamed: "仅命名",
		loading: (progressText: string) => `加载中 ${progressText}`,
		searchRegexHint: "re:<模式> 正则",
		searchExactHint: '"短语" 精确匹配',
		deleteConfirm: "确认删除这个会话？",
		noNamedAll: (toggleKey: string) => `  没有已命名会话。按 ${toggleKey} 查看全部。`,
		noNamedCurrent: (toggleKey: string) => `  当前目录没有已命名会话。按 ${toggleKey} 查看全部，或按 Tab 查看全局。`,
		noSessionsAll: "  没有找到会话",
		noSessionsCurrent: "  当前目录没有会话。按 Tab 查看全部。",
		deleteCurrentError: "不能删除当前正在使用的会话",
		trashed: "会话已移到回收站",
		deleted: "会话已删除",
		failedLoad: (message: string) => `加载会话失败：${message}`,
		renameTitle: "重命名会话",
		renameInputLabel: "会话名（留空则移除）：",
		renameSave: "保存",
		renameCancel: "取消",
		relativeNow: "刚刚",
		relativeMinutes: (value: number) => `${value}分`,
		relativeHours: (value: number) => `${value}小时`,
		relativeDays: (value: number) => `${value}天`,
		relativeWeeks: (value: number) => `${value}周`,
		relativeMonths: (value: number) => `${value}月`,
		relativeYears: (value: number) => `${value}年`,
	},
	loginDialog: {
		title: (providerName: string) => `登录 ${providerName}`,
		cancelled: "登录已取消",
		clickHint: (modifier: string) => `${modifier}+单击打开`,
		cancel: "取消",
		submit: "提交",
		close: "关闭",
		example: (placeholder: string) => `例如：${placeholder}`,
	},
	themeSelector: {
		current: "（当前）",
	},
	extensionSelector: {
		navigate: "上下移动",
		select: "确认",
		cancel: "取消",
	},
	scopedModelsSelector: {
		title: "模型范围配置",
		sessionOnly: (saveKey: string) => `仅当前会话生效。按 ${saveKey} 可保存到 settings。`,
		noMatches: "  没有匹配的模型",
		modelName: (name: string) => `  模型名称：${name}`,
		allEnabled: "全部启用",
		enabledCount: (enabled: number, total: number) => `${enabled}/${total} 已启用`,
		toggle: "切换",
		enableAll: "全开",
		clearAll: "清空",
		provider: "同 provider",
		reorder: "重排",
		save: "保存",
		unsaved: "（未保存）",
	},
	thinkingSelector: {
		off: "不启用思考",
		minimal: "极简思考（约 1k tokens）",
		low: "轻量思考（约 2k tokens）",
		medium: "中等思考（约 8k tokens）",
		high: "深入思考（约 16k tokens）",
		xhigh: "最强思考（约 32k tokens）",
	},
	treeSelector: {
		title: "会话树",
		move: "移动",
		page: "翻页",
		foldBranch: "折叠/分支",
		label: "标签",
		filters: "筛选",
		cycle: "循环",
		labelTime: "标签时间",
		searchPrompt: "输入即可搜索：",
		labelInput: "标签（留空则移除）：",
		save: "保存",
		cancel: "取消",
		userPrefix: "用户：",
		assistantPrefix: "助手：",
		assistantAborted: "（已中止）",
		assistantNoContent: "（无内容）",
		compaction: (tokensInThousands: number) => `[压缩: ${tokensInThousands}k tokens]`,
		branchSummaryPrefix: "[分支摘要]: ",
		model: (modelId: string) => `[模型: ${modelId}]`,
		thinking: (level: string) => `[思考: ${level}]`,
		custom: (customType: string) => `[自定义: ${customType}]`,
		labelEntry: (label: string) => `[标签: ${label}]`,
		labelCleared: "[标签: 已清空]",
		titleEntry: (title: string) => `[标题: ${title}]`,
		titleEmpty: "[标题: 空]",
	},
	userMessageSelector: {
		noMessages: "  没有可用于分叉的用户消息",
		messagePosition: (position: number, total: number) => `  第 ${position} 条 / 共 ${total} 条消息`,
		title: "从消息分叉",
		description: "选择一条用户消息，把到该节点为止的当前路径复制到新会话中",
	},
	configSelector: {
		resourceConfiguration: "资源配置",
		filterResources: "输入即可筛选资源",
		toggle: "切换启用状态",
		close: "关闭",
		noResources: "  没有找到资源",
		userSettings: "用户设置",
		projectSettings: "项目设置",
		userDir: (baseDir: string) => `用户 (${baseDir})`,
		projectDir: (baseDir: string) => `项目 (${baseDir})`,
		userDefaultDir: "用户 (~/.lumen/agent/)",
		projectDefaultDir: "项目 (.lumen/)",
		extensions: "扩展",
		skills: "技能",
		prompts: "提示模板",
		themes: "主题",
	},
	settingsSelector: {
		submenuConfirm: "确认",
		submenuCancel: "返回",
		warningsConfigure: "配置",
	},
	bashExecution: {
		running: (cancelKey: string) => `正在运行...（${cancelKey} 可取消）`,
		cancelled: "（已取消）",
		moreLines: (count: number) => `… 还有 ${count} 行`,
	},
	toolSummary: {
		running: "运行中…",
		completed: (parts: string) => `已完成 ${parts}`,
		runningBatch: (parts: string) => `进行中 ${parts}`,
	},
} as const;
